### ISSUE TITLE
Probing only for Shoot namespaces

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/dependency-watchdog#14]
**Describe the bug:**
Currently the dependency-watchdog-prober tries executing probes for all namespaces see: 

![image](https://user-images.githubusercontent.com/33809186/82060052-1e588f00-96c7-11ea-9cbe-63e27ed14e38.png)

**Expected behaviour:**
Only execute probes for Shoot namespace.
Filter for those labels on the namespace:
```    
garden.sapcloud.io/role: shoot
gardener.cloud/role: shoot
```

**How To Reproduce (as minimally and precisely as possible):**
Just check the logs of the  dependency-watchdog-prober running in the garden cluster.

**Logs:**

**Screenshots (if applicable):**

**Anything else we need to know?**:

**Comment by amshuman-kr** [comment]
@danielfoehrKn These are just logs from the setting up of the probe. Whenever a new namespace is created, the watchdog tries to setup a goroutine to probe it's shoot apiserver by looking up the configured kubeconfig secrets. This is logs from that part of the code. If the secrets are not available (shoot control-plane is still coming up) then no probing goroutine is setup.

As part of #15, some of this will be optimized and I will also reduce the logging level for namespaces that do not (at least not yet) have the kubeconfig secrets.

Shall I close this in favour of #15?

**Comment by danielfoehrKn** [comment]
Alright, thanks for the info.
