### ISSUE TITLE
[Feature] Improve log

### ISSUE THREAD

**Issue by rfranzke** [gardener/dependency-watchdog#21]
I see logs

```
I0624 07:14:37.741015       1 prober.go:419] Scaling down shoot-kube-apiserver/shoot--dev--foo: replicas=0: successful
```

that are suggesting that DWD scales down the kube-apiserver. Actually, it correctly scaled down the kube-controller-manager, but the log leads to confusion. Please log the `dependentScales` to make clear what is being scaled down.

**Comment by ialidzhikov** [comment]
+1
