### ISSUE TITLE
[BUG] dependency-watchdog scales KCM to 0 when creating a cluster on a seed running kubernetes 1.22.2

### ISSUE THREAD

**Issue by plkokanov** [gardener/dependency-watchdog#35]
**Describe the bug:**
After creating a cluster on a seed that runs on kubernetes v1.22.2 the dependency-watchdog scales down the shoot's KCM to 0 because its external probe for the kube-apiserver fails. After around 15 minutes the external probe starts succeeding and the dependency-watchdog scales KCM back to 1.

**Expected behaviour:**
The dependency-watchdog's external probe to succeed and the KCM to not get scaled.

**How To Reproduce (as minimally and precisely as possible):**
Create a shoot cluster on a seed that runs on kubernetes v1.22.2. Wait for the KCM deployment to get created with 1 replica and afterwards observe that it gets scaled down to 0 replicas.

**Logs:**
```
I1025 12:20:43.601789       1 scaler.go:72] Update event on cluster: shoot--<project>--<name>
I1025 12:20:46.564940       1 reflector.go:268] k8s.io/client-go/informers/factory.go:135: forcing resync
I1025 12:20:54.122195       1 prober.go:360] shoot-kube-apiserver/shoot--<project>--<name>/internal: probe succeeded
I1025 12:20:54.122214       1 prober.go:375] shoot-kube-apiserver/shoot--<project>--<name>/internal: probe result: &scaler.probeResult{lastError:error(nil), resultRun:3}
I1025 12:21:04.122542       1 prober.go:363] shoot-kube-apiserver/shoot--<project>--<name>/external: probe failed with error: Get https://api.<shoot-name>.<project>.internal.dev.k8s.ondemand.com/version?timeout=10s: context deadline exceeded (Client.Timeout exceeded while awaiting headers). Will retry...
I1025 12:21:04.122576       1 prober.go:375] shoot-kube-apiserver/shoot--<project>--<name>/external: probe result: &scaler.probeResult{lastError:(*url.Error)(0xc00156cf60), resultRun:3}
I1025 12:21:04.122603       1 prober.go:405] Scaling down dependents of shoot-kube-apiserver/shoot--<project>--<name>: apps/v1.Deployment/kube-controller-manager: replicas=0: in progress...
I1025 12:21:05.277701       1 prober.go:476] Scaling down dependents of shoot-kube-apiserver/shoot--<project>--<name>: apps/v1.Deployment/kube-controller-manager: replicas=0: successful
```

**Anything else we need to know?**:
After some time, around 30 minutes, the kube-apiserver external probe starts working again and KCM gets scaled back to 1.

**Environment**:
- Gardener version: master
- Seed kubernetes version (use `kubectl version`): v1.22.2
- Cloud provider or hardware configuration: so far observed on GCP and Azure
- Others:

**Comment by ashwani2k** [comment]
@plkokanov  -- I've also seen it during one of my local testing but it was mainly happening -- 
- When machine creation has failed for some reason (this was observed with v1.35 upgrade and machines were in pending state, which was somehow resolved with v1.35.1 ) 
- When I tried to delete such a cluster where machine creation was in pending state and not progressing, in such a case the KCM was continuously scale down and the deletion won't progress beyond a certain point. 
Have you noticed this in similar condition. 

Also I noticed there is already a known issue #25 by @amshuman-kr  on something similar to what I've observed. 
Just wanted to confirm if you face the similar situation.

**Comment by amshuman-kr** [comment]
> After some time, around 30 minutes, the kube-apiserver external probe starts working again and KCM gets scaled back to 1.

The external probe initially failing and then later succeeding after 15-30m seems to suggest DNS issues. Could it similar to #22?

I don't think #25 is relevant here because that may manifest only during shoot deletion.

**Comment by plkokanov** [comment]
I also suspected that it could be caused by the DNS, but it also happens when a cluster is created (so no DNS switch). I will investigate further next week, though

**Comment by plkokanov** [comment]
Update: this issue does not seem to happen on AWS (coincidentally route53 is where the DNS records for my tests are created). And since last week I'm also having trouble to reproduce it on GCP and Azure

**Comment by ialidzhikov** [comment]
This issue strikes again on Azure.

![Screenshot 2022-01-07 at 11 23 12](https://user-images.githubusercontent.com/9372594/148522331-d055c7f5-ede5-4caf-9610-049e8b193cb0.png)


In the last 14 days all `shoot-release-test-suite` runs (against a Shoot that is just migrated) failed.
Symptoms are the same - KCM is wrongly scaled down to `0` by dependency-watchdog. Log output from test execution:
```
{"level":"info","msg":"Deployment kube-scheduler is healthy with 1/1 replicas","ts":"2022-01-04T16:26:29.160Z"}
{"level":"info","msg":"Deployment kube-controller-manager is healthy with 0/0 replicas","ts":"2022-01-04T16:26:29.160Z"}
{"level":"info","msg":"Deployment kube-apiserver is healthy with 1/1 replicas","ts":"2022-01-04T16:26:29.160Z"}
```

**Comment by kris94** [comment]
I was able to reproduce this issue and once I took a tcp dump to see where the connection is breaking. From what I see it seems that the API server url is resolved correctly and a packet is sent to the right place, however there are not any packets coming back to the dependency-watchdog.
<img width="1727" alt="Screenshot 2022-03-04 at 10 19 34" src="https://user-images.githubusercontent.com/64421756/156726416-0ba763ad-2e25-49fc-b4c0-672034d76284.png">

**Comment by ScheererJ** [comment]
I tried to reproduce the issue several times with a seed with kubernetes v1.22.7 on gcp creating new clusters while monitoring the `dependency-watchdog` logs and the `kube-controller-manager` availability. Unfortunately, I could not reproduce this issue.
Our somewhat recent changes (a couple of weeks ago) to improve istio-ingressgateway stability might have helped fixing this issue or I was just lucky/unlucky so that it always succeeds for me.
Please report if this issue is still occurring even for the migration scenario.

**Comment by plkokanov** [comment]
I found what the reason for this error is: https://github.com/gardener/gardener/pull/5995#issuecomment-1138921606 
And I also opened an issue: https://github.com/gardener/gardener/issues/6036
So I will close this now as this will be addressed in `gardener`.
