### ISSUE TITLE
[Feature] Ensures the selectors for deployments used by DWD abide to the Gardener Extension concept 

### ISSUE THREAD

**Issue by ashwani2k** [gardener/dependency-watchdog#42]
**Feature (What you would like to be added):**
With GEP-01 (extensibility) cloudprovider specific details are extracted to extensions. 
With the introduction of scaleRef dependencies in the release v0.7.0. The component model of gardener/gardener is broken as it requires it to have knowledge of `machine-controller-manager` deployment name. Details can be checked [here](https://github.com/gardener/gardener/pull/5497/files/6e52ca264c134a9857925af5dbbab13174fb7b16#r816778201).

As currently its resolved by adding a constant in the g/g api types to identify `MCMDeploymentName` as design with an alternate selection criteria will require a re-design of concepts which the basic functionality of DWD relies on. 

**Motivation (Why is this needed?):**
To ensure we don't break the contract and keep the separation of concern design principle in play. 

**Approach/Hint to the implement solution (optional):**

**Comment by ialidzhikov** [comment]
Let's close for now as currently I don't know of a provider extension that does not use MCM currently. If there is one in the future, we could think of a approach similar the logging extensibility where provider extensions provide a ConfigMap (filters, parsers) with a well-known label and these ConfigMaps are aggregated and passed to the fluent-bit on Seed bootstrap. Let's for now do not introduce such complexity when there is no real need for it.

/close
