### ISSUE TITLE
[BUG] DWD should scale the resources up to allow hibernation or deletion of the cluster to finish

### ISSUE THREAD

**Issue by ashwani2k** [gardener/dependency-watchdog#45]
**Describe the bug:**

Currently dependency watchdog acts on 2 events:  
1. cluster-state change and 
2. secret-update. 

In cases where the events are as a result of cluster state change from active to hibernated|deleted, DWD probe is stopped for such clusters. 
However,  if the DWD probe has already acted on the resources managed by it and scaled them down due unavailability of api-server then it makes the operations of Hibernation or Delete for the shoot fail. This happens as once the cluster is hibernated or deleted the DWD probe is cancelled and if before it was stopped if the KCM/MCM/CA deployments were scaled down they are left as is. 
This result in operation like hibernation and deletion to fail as they depend on availability of KCM/MCM.

**Expected behaviour:**
Shoot hibernation or deletion should be possible even for clusters where external-api server probe failure has brought down KCM/MCM as per the DWD contract. 

**How To Reproduce (as minimally and precisely as possible):**
1. Change the DWD secret for external probe with replacing the server url with a wrong address. This will result in external probe to fail. 
2.Let the DWD probe fail the external probe and scale down the KCM/MCM/CA deployments. 
3. Hibernate the cluster --> This will fail as it will not be able to remove the machines as MCM is down. 

**Logs:**

**Screenshots (if applicable):**

**Anything else we need to know?**:

**Comment by vlerenc** [comment]
Who can help here to avoid further manual DoD intervention @ashwani2k ?

**Comment by ialidzhikov** [comment]
Looks like this issue should be tackled in the extension library. My expectations:
- DWD stops tracking the Shoot as it is hibernating
- gardenlet and the provider extensions to scale up KCM and MCM as part of the Shoot and Worker reconciliation

At first look it seems that the provider extension won't do the scale up for the MCM when MCM is scaled down by DWD right before the hibernation.

https://github.com/gardener/gardener/blob/80c9a619e3d5e68f6fb5a4fcdb016004c34fbc64/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go#L58-L63

**Comment by unmarshall** [comment]
Yes this is agreed. This is also the current behavior where DWD stops the probe for clusters which have been marked for hibernation or have a `spec.deletionTimestamp` set. So in the event where DWD scaled down MCM and KCM then it will be brought up during the shoot/worker reconciliation.

**Comment by ashwani2k** [comment]
Just want to highlight that we need to do this handling for both `hibernation` and `deletion` of shoots. 

So, If I understand correctly if we enhance the configuration later to add more Resources to be managed by DWD which can block as shoot hibernation and deletion then we need to do the same for them as well.

**Comment by unmarshall** [comment]
yes that is my understanding a well. Ideally it should be part of the shoot/worker reconciliation.
