### ISSUE TITLE
[BUG] DWD wrongfully scales down resources when api-server takes more than 10s to respond

### ISSUE THREAD

**Issue by ashwani2k** [gardener/dependency-watchdog#55]
**Describe the bug:**
Currently the DWD probe has a timeout of 10s which at times fails when there is request latency of higher than 10s. 
In such cases the api-server is reachable and kubelet is also able to update it's heartbeat, however DWD assumes that api-server is not reachable and bring the KCM/MCM/CA down. 

**Expected behaviour:**
DWD should honor the same timeout as set for kubelet. 

**How To Reproduce (as minimally and precisely as possible):**
Create load on the kube-apiserver with high request load resulting latency values beyond 10s to respond. 
This should eventually fail the external probe and will eventually bring down the components although the api-server is reachable from the node albeit slow. 

**Logs:**

**Screenshots (if applicable):**

**Anything else we need to know?**:

**Comment by unmarshall** [comment]
**Kubelet configuration:**
`nodeStatusUpdateFrequency` is set to 10s - this is the duration that kubelet will compute node status.
`nodeStatusReportFrequency` is set to 0s
There is no value set for `nodeLeaseDurationSeconds` which is defaulted to 40s. This is the duration for which the node lease is valid. The default duration for kubelet to update its lease is 10s.

There is no explicit timeout set on the client that is used by the kubelet to reach KAPI.

**On KCM:**
`node-monitor-grace-period` is set to 2m0s (120sec). This means that KCM only moves a node to `Unknown` state.

**On DWD**
Current configurations:
* Frequency with which probe is called is 10s (sliding - which means computes 10s after the current sync probe function call returns).
* Total timeout for probe is 10s

We will change this to:
* Total timeout for probe: 30s
In the edge case where the KAPI fails to respond in 30s, then with a failure threshold of 3, total time that the probe will wait will be (30+10)*3 = 120 sec before it breaches the failure threshold and initiates scaling down operation. This is in line with total time KCM allows the kubelet to update its lease as well.

**Reference links:**
* https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
* https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/

**Comment by unmarshall** [comment]
As part of the fix:

- Default timeout for client used to probe the kube API server is now set to 30s (earlier 10s)
- A new configuration property (optional) has been introduced `probeTimeoutSeconds`. The default value of 30s can be overriden by explicitly specifying a new value via this configuration property.
