### ISSUE TITLE
DWD is seed-centrally installed/configured, but shoots have individual node monitor grace periods

### ISSUE THREAD

**Issue by vlerenc** [gardener/dependency-watchdog#79]
**What would you like to be added**:
DWD is seed-centrally installed/configured, but shoots have individual node monitor grace periods. Unfortunately, that's exactly what matters most when it comes to disabling KCM before it can run amok, should for example the API server become unreachable to the `kubelet`s. It won't/can't do it's job and disable KCM before it already puts everything into `Unknown`/`NotReady` and thereby triggers a chain of events that we would rather like to avoid.

What can we do? If shoot-specific configurations are too complex/require too much effort/take too much time, can we then simply (and safely? and quickly?) change the probe interval from `30s` to probably `10s`, so that it fits a `40s` `node-monitor-grace-period` (default for Kubernetes)? Only people who configure that more aggressively (below that value; unless we forbid that) would then have no safeguard anymore, but everyone else would be "protected".

**Comment by vlerenc** [comment]
Let's close this ticket. The only solutions that come to mind would be:
- Let DWD watch separate configurations per shoot cluster
- Have DWD deployed once per shoot cluster

We do not have the bandwidth to work on this and we have actually a reasonable solution in place that only fails if an end user configures the node grace period to be lower than our/official default of `40s`. But in this case, DWD cannot really help anyway, because there is a limit to how long an issue must be first observed before DWD can do something or else we risk flapping behaviour which is even less desirable.

/close So, let's close this as won't fix (now that we have reduced our default node grace period to `40s` (like Kubernetes upstream)).

**Comment by vlerenc** [comment]
Let's close this ticket. The only solutions that come to mind would be:
- Let DWD watch separate configurations per shoot cluster
- Have DWD deployed once per shoot cluster

We do not have the bandwidth to work on this and we have actually a reasonable solution in place that only fails if an end user configures the node grace period to be lower than our/official default of `40s`. But in this case, DWD cannot really help anyway, because there is a limit to how long an issue must be first observed before DWD can do something or else we risk flapping behaviour which is even less desirable.

So, let's close this as won't fix (now that we have reduced our default node grace period to `40s` (like Kubernetes upstream)).

/close

**Comment by unmarshall** [comment]
In [PR](https://github.com/gardener/dependency-watchdog/pull/94) we now honour the `NodeMonitorGracePeriod` that is set in the shoot by a customer. See [here](https://github.com/gardener/dependency-watchdog/pull/94/files#diff-edadd71d8bc1ca4e7e667f568adf4f277d84963bdc2a0cd40bddac2727587469R185).
By default there will be one prober configuration that will be defined at the seed level and that will be treated as a default configuration for all probers (one per shoot control plane). If any shoot has explicitly set `NodeMonitorGracePeriod` then we will get that value and use that for only that shoot.

**Comment by unmarshall** [comment]
https://github.com/gardener/dependency-watchdog/pull/94 is now merged. Closing this issue as well.
/close
